dist: xenial

notifications:
  email: false

git:
  depth: 5
  submodules: false

language: python

cache:
  - pip

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

python: 3.7

install:
  - pip install -r requirements-ci.txt

jobs:
  include:
    - stage: HCML 2019
      before_script: pip install -r HCML_2019/requirements.txt
      script: pytest --nbval HCML_2019/ --sanitize-with nbval_sanitize_file
